# Generated by Django 4.2.16 on 2024-09-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfc',
            name='idUser',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
