# Generated by Django 4.2.16 on 2024-09-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0002_nfc_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfc',
            name='nombre',
            field=models.CharField(default='hola', max_length=30),
            preserve_default=False,
        ),
    ]
