# Generated by Django 4.2.16 on 2024-11-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0003_nfc_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the product purchased.', max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, help_text='Price of the individual product.', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the product purchased.')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount of the purchase.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the purchase was made.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the purchase was last updated.')),
                ('item', models.ForeignKey(help_text='The item purchased.', on_delete=django.db.models.deletion.CASCADE, to='nfc.purchaseitem')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-created_at'],
            },
        ),
    ]
