# Generated by Django 4.2.16 on 2024-11-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0004_purchaseitem_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='helper',
            field=models.CharField(default=1, help_text='Helper field to test the model.', max_length=255),
            preserve_default=False,
        ),
    ]
