# Generated by Django 4.2.16 on 2024-11-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0005_purchaseitem_helper'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the product purchased.', max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, help_text='Price of the individual product.', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the product purchased.')),
                ('helper', models.CharField(help_text='Helper field to test the model.', max_length=255)),
            ],
            options={
                'verbose_name': 'Purchase Log',
                'verbose_name_plural': 'Purchase Logs',
            },
        ),
    ]
